# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI geeup

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies (Mac)
        continue-on-error: true
        run: python -m pip install --upgrade pip
          pip install -U pip setuptools
          pip install wheel
        if: matrix.os == 'macos-latest'
      - name: Install Dependencies (Windows)
        continue-on-error: true
        run: python -m pip install --upgrade pip
          pip install -U pip setuptools
          pip install wheel
        if: matrix.os == 'windows-latest'
      - name: Test package
        run: |
          pip install --upgrade pip
          python setup.py install
          geeup -h
